storekeeper-company/magento2-plugin

- Api/Webhook/Webhook.php
- Helper/Api/Orders.php
- composer.json
Refactored payload filling logic, divided main code pieces into separate private methods. //TODO Work on config products
> 8677djn7f bundle/simple products combined

- Controller/Checkout/Redirect.php
- Model/ConfigProvider.php
- view/frontend/web/template/payment/storekeeper_payment.html
- Resolved bug with payment id 0 on storekeepr redirect
- Added store logo image if payment logo missing
- Resolved bug with hidden payment method duplicates under payment options
> 861mkv8kv adding extra payment methods

- Cron/Orders.php
- etc/crontab.xml
- etc/di.xml
Moved cronjob from symfony console to Magento cron entity
> 85zrzmqrq cronjob entity

- Model/Export/AbstractExportManager.php
- Model/Export/AttributeExportManager.php
- Model/Export/AttributeOptionExportManager.php
- Model/Export/AttributeSetExportManager.php
- Model/Export/BlueprintExportManager.php
- Model/Export/CategoryExportManager.php
- Model/Export/Consumer.php
- Model/Export/CsvFileContent.php
- Model/Export/CustomerExportManager.php
- Model/Export/ProductExportManager.php
- Test/Integration/Export/AttributeExportDataTest.php
- Test/Integration/Export/AttributeOptionExportDataTest.php
- Test/Integration/Export/BlueprintExportDataTest.php
- Test/Integration/Export/CategoryExportDataTest.php
- Test/Integration/Export/CustomerExportDataTest.php
- Test/Integration/Export/ProductExportDataTest.php
- Added alias formatting for attribute set column;
- Filtered out attributes without label;
- Updated integration test for attribute options export with product attribute fixture. Corrected namespaces in Export And Test/Integration folders
> Attribute Export updates

- Test/Integration/OrderCreationDownloadableTest.php
- Test/Integration/_files/order_with_downloadable_product.php
- Added Integration test class and required fixtures in order to test sync of order with downloadable type order item
> 8694eqgy8 Sync Order from Shop: product type integration tests

- Api/Data/EventLogInterface.php
- Api/Data/EventLogSearchResultsInterface.php
- Api/EventLogRepositoryInterface.php
- Api/Webhook/Webhook.php
- Controller/Adminhtml/EventLog/Index.php
- Model/EventLog.php
- Model/EventLogRepository.php
- Model/ResourceModel/EventLog.php
- Model/ResourceModel/EventLog/Collection.php
- Test/Integration/WebhookTest.php
- etc/acl.xml
- etc/adminhtml/menu.xml
- etc/adminhtml/routes.xml
- etc/db_schema.xml
- etc/di.xml
- view/adminhtml/layout/storekeeper_storekeeper_eventlog_index.xml
- view/adminhtml/ui_component/storekeeper_storekeeper_eventlog_listing.xml
- Created model for Event logs with admin grid
- Updated Webhook test class with data for Event logging
> CU-8694eqn1x Event Logs

- Api/OrderApiClient.php
- Helper/Api/Products.php
- Test/Integration/ImportExistingProduct.php
- Implemented ImportExistingProduct Integration test, which covers creation of 3 different attribute types during import from SK. 
-  Minor refactoring of Api/Products class
**Please review it after PR #57** , because this PR have merged branch with Attribute import logic from that PR
> Cu 8694eqg1h attribute import integration test

- Helper/Api/Attributes.php
- Helper/Api/Products.php
- Test/Integration/ImportExistingProduct.php
- Added attribute set creation during product sync update, performed minor refactoring of attributes saving, by optimizing work with attribute set
- Extended product import integration test with assertion data for attributes set creation
**Please review it after PR #58, because this PR have merged branch with integration test for attribute creation during product import**
> Cu 8694qnez1 Attribute set creation during import

- Helper/Api/Attributes.php
- Helper/Api/Products.php
- Test/Integration/ImportExistingProduct.php
- Test/Integration/ImportNewConfigurableProduct.php
- Created integration test for import of new config product, minor code improvements in Api/Attributes and Api/Products helpers
- Updated ImportExistingProduct integration test according to changes in processProductAttributes() method
> Cu 8694eqfkb Product with variations (magento configurable products) integration test

- Api/AttributeApiClient.php
- Helper/Api/Orders.php
- Test/Integration/AbstractTestCase.php
- Corrected discount payload in order to receive name and sku of discount based on rule name, instead of coupon code or description (those are not required fields and might be empty)
> CU-861n2mugw Fixed name and sku for discount item payload

- Api/Webhook/Webhook.php
- Helper/Config.php
- Helper/Info.php
- Expanded infohook 'extra' data with: name, description, now_date, active_theme, language, system_status
- Moved out all infohook related code from Api/Webhook class into separate helper Helper/Info in order to keep code clean
- Node 'image_variants' left out of scope of current task due to exact way of SK CDN integration is still open question
> Cu 8694eqcrb add and verify new infohook data

- Api/OrderApiClient.php
- Helper/Config.php
- Model/Carrier/Storekeeper.php
- README.md
- etc/adminhtml/system.xml
- etc/config.xml
- i18n/en_US.csv
- i18n/nl_NL.csv
- Added custom shipping carrier which implements connection with StoreKeeper Shipping Methods gateway
> Cu 8694eqmnw develop custom shipping carrier

- Api/OrderApiClient.php
- Helper/Config.php
- Model/Carrier/Storekeeper.php
- Test/Integration/CarrierTest.php
- Test/Integration/CarrierTestAbstract.php
- etc/adminhtml/system.xml
- etc/config.xml
Created integration test for shipping carrier covering next scenarios:
- Carrier available and applicable;
- Carrier available and not applicable to cart/order;
- Carrier enabled and customer's country is not in a list;
- Free shipping when order total > 'free_from_value_wt';
- Exception handling during process of collect rates;
> CU-8694eqmtm  Integration test for shipping carrier

- Helper/Api/Auth.php
- Observers/CheckoutSubmitAllAfterObserver.php
- Observers/SalesOrderCreditMemoSaveAfterObserver.php
- Observers/SalesOrderInvoicePayObserver.php
- Observers/SalesOrderSaveBeforeObserver.php
- Restricted order sync for sync modes outside of 'orders' and 'all'
> CU-8694wv8a3 Disallow order sync on sync mode 'none' and 'products'

- Controller/Adminhtml/Order/MassSyncOrders.php
- view/adminhtml/ui_component/sales_order_grid.xml
- Updated mass-action for orders sync - update both failed and not yet processed order, record into failed sync order db table only failed cases
> CU-8694wv8kf Update 'Resync failed orders' mass-action

- Model/Export/AttributeExportManager.php
- Handled list of exportable attributes during attribute export in a same way as during product export
> CU-8694wv9cm  Extend list of ignored product attributes during import

- Helper/Api/Products.php
- Corrected logic for assigning main and gallery product images and cdn image url getter
> CU-8694x48m6 Correct product images sync

- Api/OrderApiClient.php
- Api/PaymentApiClient.php
- Controller/Checkout/Finish.php
- Controller/Checkout/Redirect.php
- Helper/Api/Orders.php
- Model/Invoice.php
- Observers/CheckoutSubmitAllAfterObserver.php
- Observers/SalesOrderCreditMemoSaveAfterObserver.php
- Observers/SalesOrderInvoicePayObserver.php
- Observers/SalesOrderSaveBeforeObserver.php
- Test/Integration/AbstractTestCase.php
- Updated part of module responsible for adding order sync tasks to queue and work with custom order attributes during order sync;
- Fixed order update api wrapper method;
- Adjusted order creation integration test;
> Cu 8694zgq2j order sync data conflict during consumer queues processing

- Helper/Api/Orders.php
- Observers/SalesOrderShipmentSaveBefore.php
- Test/Integration/ShipmentCreationTest.php
- Test/Integration/_files/order_shipping.php
- Created shipment Integration trests which validates shipment creation in sk backoffice by asserting storekeeper_shipment_id value added to order entity
> CU-8694eqmtm Adjusted order creation integration test

- Model/ConfigProvider.php
- Ui/DataProvider/ExportFileDataProvider.php
- Fixed error on checkout when module not connected to SK backoffice;
- Fixed missing variable on Storekeeper Import/Export grid which appears when there is no export records.
> CU-8694mf5ad Preparations for pilot customer

- Model/Export/CategoryExportManager.php
- Test/Integration/Export/CategoryExportDataTest.php
- Test/Integration/_files/categories.php
- Updated category slug from full url path to url key only;
- Actualized integration test for category export.
> Cu 86955wh2k category export update slug

- Model/Export/ProductExportManager.php
- Added file format check via Symfony's FileinfoMimeTypeGuesser;
> CU-86955wjg0 Product export: handle product with gif images

- Model/Export/CsvFileContent.php
- Model/Export/ProductExportManager.php
- Test/Integration/Export/ProductExportDataTest.php
- Test/Integration/_files/taxable_simple_product.php
- Corrected custom attributes path, label and structure of  value/value_label cells. Updated Product export integration test accordingly;
- Optimized collection slicing during csv file generating process;
- Updated integration test expected data - removed already redundant core attributes like visibility, url key etc, corrected expected data for value and value_label for brand attribute;
- Stored option_id in register/registry instead of using hardcoded value in integration test.
> Cu 86955wkrm product export correct csv structure for custom attributes

- Model/Export/ProductExportManager.php
- README.md
- Added handling of barcode attribute via sku validation in case if it is not mapped on admin area;
- Extended Readme with Export section.
> CU-86955wu5k Product export: barcode validation

- Helper/Api/Products.php
- Helper/Config.php
- Added product price tax check during product import from SK
> CU-8695717mp Product import: Incorrect price saved on Product update webhook

- Helper/Api/Attributes.php
-  Added handling of featured attributes during product import - it will mitigate incorrect behavior when magento creates new attribute for already mapped one, based on SK attribute code;
> CU-86955x96a Check effect of import from sk to magento

- Helper/Config.php
- Model/Export/ProductExportManager.php
- Reworked getTaxData() product export method in a way of getting rate based on product tax class and default country id.
> Cu 86957k3jx Product export: handle vat country based on default store country

- Model/Export/CategoryExportManager.php
- Updated category export with logic that ignores adding record for root and default categories, as well as adding parent slug fore categories that have default as parent.
> CU-86957p1qv Category export: ignore default category

- Api/OrderApiClient.php
- Controller/Checkout/Finish.php
- Helper/Api/Orders.php
- Returned updateStoreKeeperOrderStatus() api method call. Now it triggered only for canceled orders;
> Order sync: Check and fix order cancellation flow

- Helper/Api/Products.php
- Helper/ProductDescription.php
- Model/Export/ProductExportManager.php
- Test/Integration/Export/ProductExportDataTest.php
- Update method getCategoryData() - now it returns info about category with deepest nesting;
- Added method for filling extra category slugs;
- Added ignoring of default category during product export;
- Fixed handling products with empty description;
- Added 'thumbnail_label', 'url_path' and 'weight_type' core attributes to ignore list.
> Cu 8695d1f8w product export update main categoryslug and extra category slugs

- Model/Export/ProductExportManager.php
- Updated product price field content for configurable products: get cheapest assigned simple product price
> Cu 8695e7fk4 Product Import: handle configurable product price

- Model/Export/ProductExportManager.php
- Nullified stock-related information for configurable type products during export csv generation.
> CU-8695dw0ju Product Import: Error "Value should be more than 0 when in stock"

- Model/Export/CsvFileContent.php
- Changed sort order for product export from entity_id to type_id, in order to process configurable products first
> CU-8695dwfja Product Import: No variation products assinged to configurable

- Model/Export/AttributeExportManager.php
- Model/Export/BlueprintExportManager.php
- Model/Export/CsvFileContent.php
- Model/Export/ProductExportManager.php
- Reused method formatAlias in all product attribute code-related places in order to resolve issue with product attribute codes starting from capital letter.;
- Added grouping by sku to products collection to mitigate product duplicates in export csv.
> CU-8695egybu Attribute Options export: unable to create options for certain attribute 'Diameter'

- Model/Export/CsvFileContent.php
- Removed collection slicing for products collection because it conflicts with type sorting combined with media gallery data. Added grouping by entity_id - ow collection of products sorted by product type, and grouped by product id.
> CU-8695f68nk Product Export: products collection sorting with images

- Model/Export/ProductExportManager.php
- Extended logic for 'is_active' field for products with '…configurable_assign' type
> CU-8695f67cg Product Export: configurable_assign active/inactive status

- Model/Export/CategoryExportManager.php
- Updated value for 'path://published' field from hardcoded 1, to Magento's $category->getIsActive(), which returns 1 or 0
> CU-8695j3pd9 Category Export: handle 'published' field

- Helper/Api/Orders.php
- Added filter by `order_detached` filed to sk sync orders collection.
> CU-8695jr1zn Order sync: filter orders by order_detached

- Helper/Api/Products.php
- Helper/Config.php
- etc/adminhtml/system.xml
- etc/config.xml
- Added "Sync Product Images" config which handles import of images from SK to M2. Added 'No' as default value.
> CU-8695kkahu Product sync: add config which handles images sync

- Helper/ProductDescription.php
- Test/Integration/ProductDescriptionTest.php
- Extended const DISALLOWED_CONTENT for formatProductDescription() method with pattern for images with 'media url' source.
> CU-8695khp2c Product sync: Ignore description with img media tag

- Helper/Info.php
- Extended capabilities array for info hook.
> CU-8695w5c7r SK backoffice product view: sales channel url not available

- Helper/Api/Products.php
- Temporarily removed call of updateProductLinks() and updateProductLinks() methods during Product Sync process;
- Updated handling of SK product_images subarray in processImages() method;
- Removed redundant setProductToUseDefaultValues() method.
> Product sync code cleaning

- Helper/Api/Products.php
- Helper/ProductDescription.php
- Prevented isDisallowedContentExist() and processImages() methods processing null data;
- Moved attribute set processing before images.
> CU-8695we966 Product Import: products stuck in progress

- Controller/Checkout/Redirect.php
- Helper/Api/Attributes.php
- Model/Consumer.php
- Bypassed handling of unpublished attributes during product sync;
- Handled attributes without value_label;
- Added product sync hook call during product saving exception;
- Added check for float type during attribute handling;
- Removed unidentified variable from checkout redirect controller' exception area.
> CU-8695xnaqw Golive hotfixes

- Test/Integration/ImportExistingCategoryTest.php
- Created integration test which covers category data update during webhook event 'category created' processing;
> CU-8695y2jwg Category sync: Integration tests

- Api/Webhook/Connectinfo.php
- Api/Webhook/Webhook.php
- Block/Adminhtml/Form/Field/AuthKey.php
- Block/Adminhtml/Form/Field/DisconnectStore.php
- Block/Adminhtml/Form/Field/RefreshStore.php
- Block/System/Config/Connect.php
- Controller/Adminhtml/Index/Disconnect.php
- Controller/Adminhtml/Index/Index.php
- Helper/Api/Auth.php
- Helper/Api/Categories.php
- Helper/Api/Orders.php
- Helper/Info.php
- Model/Consumer.php
- Observers/CheckoutSubmitAllAfterObserver.php
- Observers/SalesOrderCreditMemoSaveAfterObserver.php
- Observers/SalesOrderInvoicePayObserver.php
- Observers/SalesOrderSaveBeforeObserver.php
- Test/Integration/OrderWithInvoiceCreationTest.php
- Test/Integration/ShipmentCreationTest.php
- Updated handling of store id across whole module in order to correctly get store scope for single shop stores, stores with one store view and multi-stores;
- Extended exception data logging for Order helper and sales_order_save_before observer;
- Updated scope in integration tests fixtures.
> Cu 869603bge import consumer handle single store and multi store modes

- Model/Export/ProductExportManager.php
- Updated method extendHeaderLabels() in order to properly populate catalog products export csv's attribute data.
> CU-86961w3vn Catalog Products Export: error during matching csv headers

- Model/Export/CustomerExportManager.php
- i18n/en_US.csv
- i18n/nl_NL.csv
- Skipped export of customers without billing and/or shipping address info (those who not placed any orders, or not filled those data).
> CU-8696395vb Customer export: stuck in progress

- Api/OrderApiClient.php
- Helper/Api/Orders.php
- etc/config.xml
- Added implementation for getListOrderShipmentsWithDetailsForHook() method for loading order shipment data;
- Changed createShipment method in order to work with with generating shipment items and trackings in magento based on sk shipment data.
> CU-8696673ec Incorrect Data Synced Back to Magento (Shipping ID Issue)
